apiVersion: v1
type: Opaque
kind: Secret
metadata:
  annotations:
  name: lockcept-dev-secret
  namespace: default
data:
  discord_token_dev: "T0RJek5UUTNNRFEwTlRJMU9EazVOemcyLllGaVo5QS4tUk4wV0dkR2w2S09PaWlhSVRNTHpFV1gxdW8="
  access_key_id: "QUtJQVQ2WUFaUERBN1RGUlVURVA="
  secret_access_key: "Zzg3Y0xFc1NEVUNBT1hYZi9XRksweUF1UUduVVBEM0hnaXREck40VQ=="

